# Generated by Django 5.0.6 on 2024-07-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_slide'),
        ('users', '0005_remove_user_is_verified_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcompletion',
            name='current_slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.slide'),
        ),
    ]
