# Generated by Django 5.0.6 on 2024-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subjectcompletion_current_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcompletion',
            name='study_completed',
            field=models.BooleanField(default=False, verbose_name='Обучение пройдено'),
        ),
    ]
