# Generated by Django 5.0.6 on 2024-08-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='subjectcompletion',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Тестирование'),
        ),
        migrations.AlterField(
            model_name='subjectcompletion',
            name='study_completed',
            field=models.BooleanField(default=False, verbose_name='Обучение'),
        ),
    ]
