# Generated by Django 5.0.6 on 2024-08-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profession_alter_subjectcompletion_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructaj',
            field=models.BooleanField(default=False, verbose_name='Инструктаж'),
        ),
    ]
