# Generated by Django 5.0.6 on 2024-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_instructaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcompletion',
            name='suspension',
            field=models.BooleanField(default=False, verbose_name='Отстранение'),
        ),
    ]
