# Generated by Django 5.0.6 on 2024-08-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_subjectcompletion_suspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcompletion',
            name='suspension',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отстранение'),
        ),
    ]
