# Generated by Django 5.0.6 on 2024-08-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_subjectcompletion_suspension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcompletion',
            name='suspension',
        ),
    ]
