# Generated by Django 5.0.6 on 2024-08-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_notification_options_alter_rating_options'),
        ('users', '0013_remove_subjectcompletion_suspension'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(null=True, verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='main.question')),
                ('user_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='users.subjectcompletion')),
            ],
        ),
    ]
