# Generated by Django 5.0.6 on 2024-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.PositiveIntegerField(null=True, verbose_name='Выбранный ответ'),
        ),
    ]
