# Generated by Django 5.0.6 on 2024-08-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_useranswer_options_sentmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentmessage',
            options={'verbose_name': 'Количество попыток для отправки сообщений', 'verbose_name_plural': 'Количество попыток для отправки сообщений'},
        ),
        migrations.AddField(
            model_name='subjectcompletion',
            name='notice',
            field=models.TextField(blank=True, null=True, verbose_name='Уведомление'),
        ),
    ]
