# Generated by Django 5.0.6 on 2024-08-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_sentmessage_options_subjectcompletion_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcompletion',
            name='notice',
        ),
    ]
