# Generated by Django 5.0.6 on 2024-11-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_uploadfiles_file'),
        ('users', '0024_alter_user_cat2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='main.departments', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('leader', 'Руководитель'), ('medic', 'Медик'), ('worker', 'Рабочий'), ('administration', 'Административный персонал')], max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
