# Generated by Django 5.0.6 on 2024-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
