# Generated by Django 5.0.6 on 2024-11-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_user_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_logout',
        ),
    ]
