# Generated by Django 5.0.6 on 2024-11-21 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
