# Generated by Django 5.0.6 on 2024-11-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_logout',
        ),
    ]
