# Generated by Django 5.1.3 on 2024-11-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_user_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
