# Generated by Django 5.1.3 on 2024-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_maildevice_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(max_length=165),
        ),
    ]
