# Generated by Django 5.1.3 on 2024-12-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_otp_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(max_length=40),
        ),
    ]
