# Generated by Django 5.1.3 on 2024-12-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_profession_alter_user_phone_alter_user_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profession', verbose_name='Профессия'),
        ),
    ]
