# Generated by Django 5.1.3 on 2024-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_user_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название средств индивидуальной защиты')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'СИЗ',
                'verbose_name_plural': 'СИЗ',
            },
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AddField(
            model_name='profession',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='siz', to='users.equipment', verbose_name='Сизы'),
        ),
    ]
