# Generated by Django 5.1.3 on 2024-12-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_equipment_alter_profession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
