# Generated by Django 5.1.3 on 2024-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_equipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.CharField(default='1', verbose_name='Количество'),
        ),
    ]
