# Generated by Django 5.1.3 on 2024-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_equipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название средств индивидуальной защиты'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
