# Generated by Django 5.1.3 on 2024-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_equipment_name_alter_equipment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание СИЗ'),
        ),
    ]
