# Generated by Django 5.1.3 on 2024-12-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_equipment_description_alter_equipment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='slug',
        ),
    ]
