# Generated by Django 5.1.3 on 2024-12-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_profession_options_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserve_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Резервный Email'),
        ),
    ]
