# Generated by Django 5.1.3 on 2024-12-25 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_delete_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('pet_name', 'Как зовут вашу любимую домашнюю животное?'), ('mother_maiden_name', 'Какое девичье имя у вашей матери?'), ('first_school', 'В какой школе вы учились в первый раз?'), ('dream_vacation', 'Какое ваше самое заветное место для отдыха?'), ('first_car', 'Какую машину вы впервые водили?')], max_length=255, unique=True, verbose_name='Вопрос безопасности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
