# Generated by Django 5.1.3 on 2024-12-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_user_secret_answer_securityquestion_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityquestion',
            old_name='answer',
            new_name='secret_answer',
        ),
    ]
