# Generated by Django 5.1.3 on 2024-12-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_alter_securityquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='question',
            field=models.CharField(choices=[('pet_name', 'Как зовут Ваше любимое домашнее животное?'), ('mother_maiden_name', 'Какая девичья фамилия у Вашей матери?'), ('first_school', 'В какой школе Вы учились в первый раз?'), ('dream_vacation', 'Какое Ваше самое заветное место для отдыха?'), ('first_car', 'Какую машину Вы впервые водили?')], max_length=255, verbose_name='Вопрос безопасности'),
        ),
    ]
