# Generated by Django 5.1.3 on 2024-12-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_securityquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.securityquestion'),
        ),
    ]
