# Generated by Django 5.1.3 on 2024-12-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_remove_securityquestion_user_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='secret_answer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='answer',
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
