# Generated by Django 5.1.3 on 2024-12-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0079_userloginhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userloginhistory",
            options={
                "verbose_name": "История входа пользователей",
                "verbose_name_plural": "История входа пользователей",
            },
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="browser",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userloginhistory",
            name="os",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
