# Generated by Django 5.0.6 on 2024-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tagpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.tagpost', verbose_name='Теги'),
        ),
    ]
