# Generated by Django 5.0.6 on 2024-06-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_answer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
