# Generated by Django 5.0.6 on 2024-06-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_test_questions_remove_test_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option1', models.CharField(max_length=200, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Вариант 2')),
                ('option3', models.CharField(max_length=200, verbose_name='Вариант 3')),
                ('option4', models.CharField(max_length=200, verbose_name='Вариант 4')),
                ('correct_option', models.IntegerField(verbose_name='Правильный вариант')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.subject', verbose_name='Предмет')),
            ],
        ),
    ]
