# Generated by Django 5.0.6 on 2024-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.SmallIntegerField(verbose_name='Правильный вариант'),
        ),
    ]
