# Generated by Django 5.0.6 on 2024-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='courses/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
