# Generated by Django 5.0.6 on 2024-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_slide_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
