# Generated by Django 5.0.6 on 2024-07-26 08:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_slide_order_alter_slide_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст слайда'),
        ),
    ]
