# Generated by Django 5.0.6 on 2024-07-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_uploadfiles_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(choices=[('first_aid', 'Первая помощь'), ('safe_method1', 'Безопасные методы работ медики'), ('safe_method2', 'Безопасные методы работ рабоч профессий'), ('suot', 'Суот'), ('siz', 'СИЗ'), ('fire_safety', 'Пожарная безопаность'), ('civil_defense', 'Гражданская оборона')], db_index=True, max_length=100, verbose_name='Наименование обучения'),
        ),
    ]
