# Generated by Django 5.0.6 on 2024-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_question_options_alter_slide_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(choices=[('first_aid', 'Первая помощь пострадавшим'), ('safe_method1', 'Безопасные методы и приемы выполнения работ для медиков'), ('safe_method2', 'Безопасные методы и приемы выполнения работ для рабочих профессий'), ('suot', 'Обучение по общим вопросам охраны труда и функционирования системы управления охраной труда'), ('siz', 'СИЗ'), ('fire_safety', 'Пожарная безопаность'), ('civil_defense', 'Гражданская оборона')], db_index=True, max_length=100, verbose_name='Наименование обучения'),
        ),
    ]
