# Generated by Django 5.0.6 on 2024-08-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
