# Generated by Django 5.0.6 on 2024-08-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_author_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
