# Generated by Django 5.0.6 on 2024-08-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
