# Generated by Django 5.0.6 on 2024-08-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ для инструктажа', 'verbose_name_plural': 'Ответы для инструктажа'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео инструктажа', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_videos', to='main.video', verbose_name='Cледующее видео'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='main.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
