# Generated by Django 5.0.6 on 2024-08-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_notification_options_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['user', '-created_at'], 'verbose_name': 'Оповещение', 'verbose_name_plural': 'Оповещения'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
    ]
