# Generated by Django 5.0.6 on 2024-09-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_notice_options_remove_subject_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
