# Generated by Django 5.0.6 on 2024-11-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_notification_comment_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='is_inpatient',
            field=models.BooleanField(default=False, verbose_name='Является стационарным отделением?'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Общий файл'),
        ),
    ]
