# Generated by Django 5.0.6 on 2024-11-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_departments_is_inpatient_uploadfiles_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='is_household',
            field=models.BooleanField(default=False, verbose_name='Есть ли в отделе ММП?'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='is_house',
            field=models.BooleanField(default=False, verbose_name='Файлы для хозяйственного отдела'),
        ),
    ]
