# Generated by Django 5.0.6 on 2024-11-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_departments_is_household_uploadfiles_is_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='is_household',
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='is_house',
        ),
    ]
