# Generated by Django 5.0.6 on 2024-11-02 12:27

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_departments_is_household_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(unique=True, upload_to=main.utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=250, verbose_name='Название файла'),
        ),
    ]
