# Generated by Django 5.0.6 on 2024-11-02 12:40

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_uploadfiles_file_alter_uploadfiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to=main.utils.get_upload_path),
        ),
    ]
