# Generated by Django 5.1.3 on 2024-11-28 10:17

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_uploadfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(max_length=250, upload_to=main.utils.get_upload_path),
        ),
    ]
